Error on (initial) file creation
octoherd/create-octoherd-script pull request #113
Opened 2023-07-06 14:24 UTC by theztefan

The `writePrettyFile` function was failing with the following error:
```
$ git init
$ git checkout -b main
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at writeFile (node:internal/fs/promises:1002:5)
    at writePrettyFile (file:///Users/s/.npm/_npx/ceeecce3ba4b8953/node_modules/create-octoherd-script/lib/write-pretty-file.js:26:9)
    at async createLicense (file:///Users/s/.npm/_npx/ceeecce3ba4b8953/node_modules/create-octoherd-script/lib/create-license.js:5:3)
    at async main (file:///Users/s/.npm/_npx/ceeecce3ba4b8953/node_modules/create-octoherd-script/cli.js:98:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
All done.
```

Please review and let me know if there are any concerns or suggestions.

2023-07-06 16:02 UTC, wolfy1339 requested changes

2023-07-06 16:02 UTC, wolfy1339 commented on lib/write-pretty-file.js
> +  const prettierContent = String(
This line and variable doesn't need to be there, you can simply await prettier in the `writeFile()` call

2023-07-06 16:04 UTC, wolfy1339 commented
The update from prettier needs to be updated to:
```ts
import * from "prettier";
```

2023-07-06 21:11 UTC, wolfy1339 commented on lib/write-pretty-file.js
> +  await writeFile(path, prettierContent);
```suggestion
  await writeFile(
    path,
    await pretier.format(content, {
      parser,
    }),
  );
```

2023-07-06 21:15 UTC, wolfy1339 commented on lib/create-license.js
> +  await writePrettyFile("LICENSE.md", content);
```suggestion
  await writePrettyFile(
    "LICENSE.md",
    getTemplateFileContent("LICENSE.md")
      .replace("{{YEAR}}", new Date().getFullYear())
      .replace("{{OWNER}}", name),
  );
```
Please revert these changes, `getTemplteFileContent()` is not async

2023-07-07 22:28 UTC, gr2m commented
I tested it locally and it all worked well now: https://github.com/gr2m/octoherd-script-just-testing



> The update from prettier needs to be updated to:
> 
> ```ts
> import * from "prettier";
> ```

That doesn't seem to be necessary? Also did you mean `import * as prettier from "prettier";`?

2023-07-07 22:29 UTC, gr2m approved these changes

2023-07-07 22:30 UTC, wolfy1339 commented
> That doesn't seem to be necessary? Also did you mean `import * as prettier from "prettier";`?

Yes, that is what i meant :sweat_smile:

It's the import that prettier recommends in it's docs due to their native ESM support

2023-07-07 22:48 UTC, gr2m commented
> It's the import that prettier recommends in it's docs due to their native ESM support

I thought I saw that recommendation but don't see it in https://prettier.io/blog/2023/07/05/3.0.0.html any longer? Did they explain why? I'm curious

Anyway, can you please update the import to 

```js
import * as prettier from "prettier";
```

and also fix the typo in `pretier.format` (should be double t)

2023-07-07 22:53 UTC, wolfy1339 commented
> I thought I saw that recommendation but don't see it in https://prettier.io/blog/2023/07/05/3.0.0.html any longer? Did they explain why? I'm curious

https://prettier.io/docs/en/api.html

2023-07-08 01:00 UTC, gr2m commented
> https://prettier.io/docs/en/api.html

yes but there is no explanation to why.

The page also shows

```js
import { format } from "prettier";
```

I'd do that instead

2023-07-10 09:40 UTC, oscard0m commented
@gr2m @wolfy1339 is the `import prettier` discussion something to be solved in the context of this PR or it can be changed in a different one?

2023-07-10 16:43 UTC, merged

2023-07-10 16:43 UTC, gr2m commented
> is the `import prettier` discussion something to be solved in the context of this PR or it can be changed in a different one?

we can fix it in a follow