fix(jsconfig): use `node16` modules
octoherd/create-octoherd-script pull request #148
Opened 2024-04-08 16:06 UTC by wolfy1339

2024-04-08 17:57 UTC, oscard0m requested changes

2024-04-08 17:57 UTC, oscard0m commented on jsconfig.json
> +    "moduleResolution": "node16"
missing `,` in L6

2024-04-08 18:00 UTC, wolfy1339 commented on jsconfig.json
> +    "moduleResolution": "node16"
Fixed

2024-04-09 13:59 UTC, oscard0m approved these changes

2024-04-09 13:59 UTC, merged